### PR TITLE
first implementation of ofxMultiKinectV2 into the adapter ofxDepthCam…

### PR DESCRIPTION
**Pull request by jonasfehr**
modified adapter ofxDepthCameraKinectV2, infrared Image and registered image are experimental. Issues using the Utility updateDepthImage

@matt: this should do it... Let me know if you could test it.

### CODE REVIEW

**Comment by mattfelsen** [comment]
Cool, this looks better, I'll try to test this soon. One thing I see though is you've modified the existing ofxDepthCameraKinectV2 class, which I was using for the ofxKinectForWindows2 addon. Instead, could you move your changes into a new ofxDepthCameraMultiKinectV2 class, so both addons can be supported?

**Comment by jonasfehr** [comment]
It's right i've moved it into this one, it is though detecting if it's a windows or a mac/linux machine and is running different code accordingly... The idea is inspired the way ofxKinect works.
I like the idea to have the adapters according the device name not the underlying addon.
What do you think?

**Comment by mattfelsen** [comment]
Yea, I agree, but there are a couple issues that make it complicated...

One is there's an assumption that if you're on Windows you'd use ofxKFW2, and otherwise ofxMultiKinectV2. But what if you want to use ofxMultiKinectV2 on Windows, which you might want to because it supports multiple devices, whereas the official Kinect 2 SDK only lets you use one. That's one of the reasons I like having control over which addon you use.

However, I was thinking about a different approach recently, one that would essentially mirror what ofVideoPlayer is doing. The pattern would be something like...

```
// you would always use this type, just like you always use ofVideoPlayer
ofxDepthCamera device; 

// then you can set the camera type
device.setCameraType(ofxDepthCameraKinect);
device.setCameraType(ofxDepthCameraKinectForWindows2);
device.setCameraType(ofxDepthCameraMultiKinectV2);
device.setCameraType(ofxDepthCameraOrbbecAstra);
// etc..
```

I'm not sure if that syntax is valid though, it might have to be something more like..

```
auto camera = make_shared<ofxDepthCamerKinect>();
auto camera = make_shared<ofxDepthCameraOrbbecAstra>();
// etc

device.setCamera(camera);
```

I'll play with it and see if it I can get it worked out

**Comment by mattfelsen** [comment]
I merged this in since it compiles & runs, though I'll hold off on merging back to `develop` since it's running slow for me (~20fps) and I want to make sure that ofxKFW2 still works on the Windows side. Feel free to continue sending PRs to this branch.

Related, I started working on a refactored approach I mentioned that mirrors the implementation of ofVideoPlayer or ofSoundPlayer. You can see what I've got in mind in the [refactor branch](https://github.com/mattfelsen/ofxDepthCamera/tree/refactor). (Note that it probably doesn't work currently, I was just working out the class hierarchy & such)

**Comment by jonasfehr** [comment]
Could be it's running slow, havn't checked this... The problem is that I had to copy the content from the graficcard to the disk, which slows down everything. If you know a faster copy method to get the picture...
To use the shader code of the examples in ofxMultiKinectV2 i had to use fbo's to become able to copy the result. also there if there is a faster way.
I'll check out the refactor branch...

**Comment by mattfelsen** [comment]
Ah that makes sense, I didn't notice that. You could check out ofxFastFboReader to read back pixels from the GPU

**Pull request merged**
